[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
version_files = [
    "VERSION",
    "include/version.h:VERSION"
]
tag_format = "v$version"
update_changelog_on_bump = true
changelog_incremental = true

[tool.commitizen.customize]
bump_pattern = "^(feat|fix|refactor|perf|BREAKING CHANGE)"
bump_map = {"BREAKING CHANGE" = "MAJOR", "feat" = "MINOR", "fix" = "PATCH", "refactor" = "PATCH", "perf" = "PATCH"}
change_type_order = ["BREAKING CHANGE", "feat", "fix", "refactor", "perf", "build", "ci", "docs", "style", "test", "chore"]
changelog_pattern = "^(feat|fix|refactor|perf|docs)"
schema_pattern = """^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)\
(\\([a-z ]+\\))?\
!?\
: .+$"""

[[tool.commitizen.customize.questions]]
type = "list"
name = "prefix"
message = "Select the type of change you are committing"
choices = [
    {value = "feat", name = "feat: A new feature"},
    {value = "fix", name = "fix: A bug fix"},
    {value = "docs", name = "docs: Documentation only changes"},
    {value = "style", name = "style: Changes that do not affect the meaning of the code"},
    {value = "refactor", name = "refactor: A code change that neither fixes a bug nor adds a feature"},
    {value = "perf", name = "perf: A code change that improves performance"},
    {value = "test", name = "test: Adding missing tests or correcting existing tests"},
    {value = "build", name = "build: Changes that affect the build system or external dependencies"},
    {value = "ci", name = "ci: Changes to CI configuration files and scripts"},
    {value = "chore", name = "chore: Other changes that don't modify src or test files"},
    {value = "revert", name = "revert: Reverts a previous commit"}
]

[[tool.commitizen.customize.questions]]
type = "input"
name = "scope"
message = "Scope of this change (press enter to skip)"

[[tool.commitizen.customize.questions]]
type = "input"
name = "subject"
message = "Short description of the change"

[[tool.commitizen.customize.questions]]
type = "input"
name = "body"
message = "Longer description of the change (press enter to skip)"

[[tool.commitizen.customize.questions]]
type = "confirm"
name = "is_breaking_change"
message = "Is this a breaking change?"
default = false

[[tool.commitizen.customize.questions]]
type = "input"
name = "footer"
message = "Footer(s). E.g: Closes #123, Refs #456"
