repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Use only system tools for C/C++
  - repo: local
    hooks:
      - id: clang-format
        name: Format C code
        entry: bash -c 'clang-format --style=file -i "$@"' --
        language: system
        files: \.(c|h)$

      - id: cppcheck
        name: Static analysis
        entry: bash -c 'cppcheck --enable=warning --suppress=missingIncludeSystem -I include "$@"' --
        language: system
        files: \.c$
        pass_filenames: true
