name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure CMake (Release)
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Create packages
        run: |
          cd build
          cmake --build . --target package
          # Rename packages with version
          VERSION=$(cat ../VERSION)
          mv *.deb better-rm_${VERSION}_amd64.deb || true
          mv *.rpm better-rm-${VERSION}-1.x86_64.rpm || true
          mv *.tar.gz better-rm-${VERSION}.tar.gz || true

      - name: Create binary tarball
        run: |
          VERSION=$(cat VERSION)
          mkdir -p better-rm-${VERSION}-linux-amd64
          cp build/better-rm better-rm-${VERSION}-linux-amd64/
          cp README.md better-rm-${VERSION}-linux-amd64/
          cp -r config better-rm-${VERSION}-linux-amd64/
          cp -r systemd better-rm-${VERSION}-linux-amd64/
          tar -czf better-rm-${VERSION}-linux-amd64.tar.gz better-rm-${VERSION}-linux-amd64/

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.deb
            build/*.rpm
            build/*.tar.gz
            better-rm-*-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.BR_PAT }}
